spring:
  config:
    activate:
      on-profile: local
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true